spring.application.name=cloudscale-order-api

cloudscale.repository.type=${CLOUDSCALE_REPOSITORY_TYPE:dynamodb}
cloudscale.dynamodb.table-name=${CLOUDSCALE_DYNAMODB_TABLE:cloudscale-dev-orders}

cloudscale.event-publishing.enabled=${CLOUDSCALE_EVENT_PUBLISHING_ENABLED:true}
cloudscale.eventbridge.bus-name=${CLOUDSCALE_EVENT_BUS:cloudscale-dev-events}
cloudscale.eventbridge.source=${CLOUDSCALE_EVENT_SOURCE:cloudscale.order-service}
